// owner: finn
// goal: where to read about a label npm cannot answer for

/** labels found by a marker file rather than a dependency, so npm cannot answer for them */
export const SITES: Record<string, string> = {
  shadcn: "https://ui.shadcn.com/docs",
  Bruno: "https://docs.usebruno.com",
  Postman: "https://www.postman.com",
  OpenAPI: "https://www.openapis.org",
  Docker: "https://docs.docker.com",
  "GitHub Actions": "https://docs.github.com/actions",
  Make: "https://www.gnu.org/software/make/manual/",
  just: "https://just.systems",
  pnpm: "https://pnpm.io",
  npm: "https://docs.npmjs.com",
  yarn: "https://yarnpkg.com",
  bun: "https://bun.sh",
  "npm shrinkwrap": "https://docs.npmjs.com/cli/commands/npm-shrinkwrap",
  Node: "https://nodejs.org/docs/latest/api/",
  Deno: "https://docs.deno.com",
  Bun: "https://bun.sh/docs",
  Workers: "https://developers.cloudflare.com/workers/",
  Turborepo: "https://turborepo.com/docs",
  Nx: "https://nx.dev",
  Turbopack: "https://turbo.build/pack",
  esm: "https://nodejs.org/api/esm.html",
  cjs: "https://nodejs.org/api/modules.html",
  kubernetes: "https://kubernetes.io/docs/home/",
  terraform: "https://developer.hashicorp.com/terraform/docs",
  compose: "https://docs.docker.com/compose/",
  Dockerfile: "https://docs.docker.com/reference/dockerfile/",
  "GitLab CI": "https://docs.gitlab.com/ci/",
  Jenkins: "https://www.jenkins.io/doc/",
  CircleCI: "https://circleci.com/docs/",
  Vercel: "https://vercel.com/docs",
  Netlify: "https://docs.netlify.com",
  tsconfig: "https://www.typescriptlang.org/tsconfig/",
  Task: "https://taskfile.dev",
  Rake: "https://ruby.github.io/rake/",
  Travis: "https://docs.travis-ci.com",
  "Azure Pipelines": "https://learn.microsoft.com/azure/devops/pipelines/",
  Drone: "https://www.drone.io",
  Insomnia: "https://docs.insomnia.rest",
  "REST client": "https://marketplace.visualstudio.com/items?itemName=humao.rest-client",
  helm: "https://helm.sh/docs/",
  PrimeReact: "https://primereact.org",
  "Claude Code": "https://docs.claude.com/en/docs/claude-code/overview",
  "AGENTS.md": "https://agents.md",
  Cursor: "https://docs.cursor.com",
  Copilot: "https://docs.github.com/copilot",
  Devin: "https://docs.devin.ai",
  aider: "https://aider.chat",
  Codex: "https://developers.openai.com/codex/",
  "Gemini CLI": "https://google-gemini.github.io/gemini-cli/",
  Windsurf: "https://docs.windsurf.com",
  Cline: "https://docs.cline.bot",
  Roo: "https://docs.roocode.com",
  Continue: "https://docs.continue.dev",
  Amp: "https://ampcode.com",
  Junie: "https://www.jetbrains.com/junie/",
  Kiro: "https://kiro.dev",
  Goose: "https://block.github.io/goose/",
  Augment: "https://docs.augmentcode.com",
  Cody: "https://sourcegraph.com/cody",
  "Amazon Q": "https://aws.amazon.com/q/developer/",
  OpenHands: "https://docs.all-hands.dev",
  CodeRabbit: "https://docs.coderabbit.ai",
  Sweep: "https://sweep.dev",
  Tabnine: "https://www.tabnine.com",
  Factory: "https://docs.factory.ai",
  SpecStory: "https://docs.specstory.com",
  MCP: "https://modelcontextprotocol.io",
  "llms.txt": "https://llmstxt.org",
}
