// owner: finn
// goal: col heading explainability

// prettier-ignore
export const HINTS: Record<string, string> = {
  Language: "grouped by file extension",
  Name: "the name used most, identities merged by email",
  Email: "the mailmap resolved address",
  File: "path inside the repo",
  loc: "lines that are neither blank nor comment",
  pct: "share of this view's total",
  share: "share of this view's total",
  comment: "comment lines, counted apart from code",
  blank: "empty lines",
  files: "files counted below here",
  chars: "characters, the whole file",
  "~tok": "estimated tokens at four characters each, low for dense code",
  nest: "mean indentation depth of code lines, a proxy for nesting",
  com: "commits touching this",
  commits: "commits touching this",
  churn: "lines added plus removed",
  added: "lines inserted",
  removed: "lines deleted",
  first: "earliest commit",
  last: "newest commit",
  date: "when it was authored",
  author: "who wrote it",
  subject: "the commit's first line",
  hash: "short commit id, click to copy",
  "#": "position in the repo's history, oldest is one",
  total: "every row, including any hidden by the fold",

  // the project metadata rows read the same table
  TypeScript: "versions asked for by the manifests",
  Strict: "off allows implicit any",
  Modules: "from the package type and the extensions used",
  Node: "engine range the manifests demand",
  Manager: "package manager, from the lockfiles and the manifest field",
  Manifests: "how many package.json files, one per workspace",
  Pinning: "a range installs whatever ships next",
  Frameworks: "what the app is built on",
  State: "how state travels through the app",
  UI: "component and styling layers",
  Content: "documents and content pipelines",
  Visuals: "charts, maps and drawing libraries",
  Data: "how it reaches other systems",
  Auth: "who the user is proven to be",
  Telemetry: "errors and metrics leaving the app",
  Ports: "found in compose, dockerfiles and scripts",
  Tools: "what turns the source into output",
  Testing: "test runners and browser drivers",
  Lint: "rules enforced on the source",
  Format: "who owns the whitespace",
  CI: "what runs on a push",
  Containers: "infrastructure files in the tree",
  Hosting: "where it looks like it deploys, from config, infrastructure, workflows and scripts",
  APIs: "checked in request collections and schemas",
  Config: "what the app expects to be given",

  // the parts a repo holds, shown as badges under the card title
  frontend: "ships a user interface, from a client framework in the manifests",
  backend: "serves or reaches other systems, from a server framework or a client library",
  cli: "a manifest declares a bin, so it installs a command",
  monorepo: "a manifest declares workspaces",
  "monorepo root": "workspaces and no dependencies of its own, so it only holds packages",
  mobile: "react native or expo",
  desktop: "electron or tauri",
  infra: "dockerfiles, compose, kubernetes or terraform in the tree",
  Assistants: "ai coding tools this repo shows a trace of",
  Signed: "commits whose author line or trailers name an ai",
  Rules: "instruction files checked in for those tools",
}
