// owner: finn
// goal: annotate stack metadata

// prettier-ignore
export const NOTES: Record<string, string> = {
  React: "component library, the default choice", "Next.js": "React with server rendering and routing, by Vercel",
  Nuxt: "Vue with server rendering", Vue: "component framework, template first",
  Svelte: "compiles components away, no runtime", SvelteKit: "Svelte with routing and server rendering",
  Angular: "full framework, opinionated and typed", Solid: "React shaped, fine grained reactivity",
  Astro: "content sites, ships almost no javascript", Remix: "React with web standard data loading",
  Preact: "React api in three kilobytes", "React Native": "React rendering to native mobile",
  Expo: "toolchain around React Native", Electron: "desktop apps in a bundled browser",
  Tauri: "desktop apps in a rust shell", Gatsby: "React static sites, largely superseded",
  Express: "the old default node server", Fastify: "faster node server, schema first",
  NestJS: "Angular shaped backend framework", Koa: "small express successor",
  Hono: "tiny server, runs on edge runtimes", hapi: "configuration first node server",
  Lambda: "functions on aws, no server to run",

  Zustand: "small store, hooks only", Redux: "the classic store, action driven",
  "Redux Toolkit": "redux with the boilerplate removed", MobX: "observable objects, no reducers",
  Jotai: "atomic state, bottom up", Recoil: "atomic state by meta, now quiet",
  Valtio: "proxy state, mutate it directly", XState: "explicit state machines",
  Pinia: "the vue store", "TanStack Query": "server cache, not really client state",
  SWR: "server cache by vercel", Apollo: "graphql client with a cache",
  Effector: "typed reactive store", NgRx: "redux for angular", Vuex: "the old vue store",
  "Nano Stores": "tiny framework agnostic store",

  Tailwind: "utility classes instead of stylesheets", shadcn: "components you copy in and own",
  MUI: "material design components", "Ant Design": "enterprise component set",
  Chakra: "accessible component set", Bootstrap: "the original css framework",
  Radix: "unstyled accessible primitives", "Base UI": "unstyled primitives, radix successor",
  "Headless UI": "unstyled primitives by tailwind", daisyUI: "tailwind component classes",
  Mantine: "components with hooks", "styled-components": "css in js, tagged templates",
  Emotion: "css in js, the other one", Bulma: "css framework, no javascript",
  PrimeReact: "large component suite", DiceUI: "component set", cva: "variant classes for components",
  NextUI: "component set on tailwind", Vuetify: "material components for vue", Ionic: "mobile shaped components",
  Sass: "css with nesting and variables", Less: "older css preprocessor", Stylus: "terse css preprocessor",
  PostCSS: "css transform pipeline", "vanilla-extract": "typed css, compiled away",
  UnoCSS: "on demand atomic css", clsx: "joins class names", classnames: "joins class names, older",

  axios: "http client, the common one", ky: "small fetch wrapper", got: "node http client",
  "node-fetch": "fetch before node had it", ofetch: "fetch wrapper by nuxt",
  Convex: "hosted reactive database and functions", Prisma: "typed orm with migrations",
  Drizzle: "sql first typed orm", Mongoose: "mongodb models", Postgres: "postgres driver",
  MySQL: "mysql driver", SQLite: "file database, in process", Redis: "in memory store and cache",
  Supabase: "hosted postgres with auth and storage", Firebase: "google hosted backend",
  Directus: "headless data platform", tRPC: "typed rpc without a schema language",
  GraphQL: "query language for apis", "Socket.IO": "realtime channels with fallbacks",
  WebSocket: "raw persistent connection", S3: "object storage on aws", Stripe: "payments",
  OpenAI: "model api", Anthropic: "model api",

  NextAuth: "auth for next, session based", "Auth.js": "framework agnostic auth",
  Clerk: "hosted auth with prebuilt ui", Auth0: "hosted identity provider",
  Passport: "auth strategies for node", JWT: "signed tokens, no session store",
  "Supabase Auth": "auth that ships with supabase", Lucia: "auth you host yourself",
  bcrypt: "password hashing",

  i18n: "translated interface strings", MDX: "markdown that can render components",
  Contentlayer: "typed content from files", Sanity: "hosted structured content",
  Contentful: "hosted headless cms", Storyblok: "hosted visual cms",
  Storybook: "components in isolation", Payload: "cms that lives in the repo",

  Sentry: "error tracking", PostHog: "product analytics and flags",
  "Vercel Analytics": "page and speed metrics", Datadog: "infrastructure monitoring",
  OpenTelemetry: "vendor neutral tracing", Mixpanel: "product analytics",
  Amplitude: "product analytics", pino: "fast json logger", winston: "configurable logger",

  Vitest: "test runner built on vite", Jest: "the long standing test runner",
  Mocha: "older test runner", Playwright: "browser tests across engines",
  Cypress: "browser tests, one engine", "Testing Library": "queries the dom as a user would",
  AVA: "concurrent test runner", Jasmine: "older assertion framework",
  Karma: "browser test runner, retired", supertest: "http assertions against a server",

  Vite: "dev server and bundler, fast", webpack: "the old bundler, still everywhere",
  Turbopack: "next's rust bundler", Rollup: "library bundler", esbuild: "very fast bundler in go",
  Parcel: "zero config bundler", Turborepo: "task cache for monorepos", Nx: "monorepo toolkit",
  Lerna: "older monorepo publisher", tsup: "library builds on esbuild", Rspack: "webpack api in rust",
  SWC: "rust compiler for typescript", Babel: "javascript compiler, plugin driven",
  Gulp: "task runner, older", Grunt: "task runner, retired", Make: "the original build tool",
  just: "a command runner, no build graph", Task: "yaml command runner", Rake: "ruby build tool",

  ESLint: "the standard linter, plugin driven", Biome: "linter and formatter in rust",
  oxlint: "very fast linter in rust", "TSLint (dead)": "retired, replaced by eslint",
  standard: "linter with fixed rules", xo: "eslint with opinions", Stylelint: "linter for css",
  Prettier: "formatter, few options on purpose", oxfmt: "formatter in rust", dprint: "pluggable formatter",

  "GitHub Actions": "ci in the repo, yaml workflows", "GitLab CI": "gitlab pipelines",
  Jenkins: "self hosted ci, older", CircleCI: "hosted ci", Travis: "hosted ci, largely retired",
  "Azure Pipelines": "microsoft ci", Drone: "container native ci",
  Vercel: "deploys on push", Netlify: "deploys on push",

  Bruno: "api collections stored as files", Postman: "api collections, hosted",
  Insomnia: "api client", "REST client": "http requests in plain files",
  OpenAPI: "machine readable api description",

  Node: "the server runtime", Bun: "faster runtime and toolkit", Deno: "secure runtime by node's author",
  Workers: "cloudflare edge runtime", pnpm: "package manager, hard linked store",
  npm: "the default package manager", yarn: "package manager, workspaces first",
  esm: "modern module syntax", cjs: "the older require syntax",

  "Claude Code": "anthropic's terminal agent, reads CLAUDE.md",
  "AGENTS.md": "tool neutral instructions, read by most agents",
  Cursor: "editor with an agent built in", Copilot: "github's completion and agent",
  Devin: "autonomous agent, commits as a bot", aider: "terminal pair programmer",
  Codex: "openai's coding agent", "Gemini CLI": "google's terminal agent",
  Windsurf: "agentic editor, formerly codeium", Cline: "agent inside vs code",
  Roo: "a cline fork", Continue: "open source editor assistant",
  Amp: "sourcegraph's agent", Junie: "jetbrains' agent", Kiro: "aws spec driven ide",
  Goose: "block's local agent", Augment: "context heavy assistant", Cody: "sourcegraph assistant",
  "Amazon Q": "aws assistant, once codewhisperer", OpenHands: "open source autonomous agent",
  CodeRabbit: "ai review bot on pull requests", Sweep: "issue to pull request bot",
  Tabnine: "completion model", Factory: "agent platform, droids",
  SpecStory: "saves agent chat history into the repo",
  MCP: "servers an agent is wired to", "llms.txt": "a page written for models to read",
  "house rules": "hand written instructions for whatever tool",
  Qwik: "resumable, ships almost no javascript", RedwoodJS: "full stack react, opinionated",
  AdonisJS: "laravel shaped node framework", Strapi: "headless cms you host",
  Medusa: "commerce backend", Keystone: "cms and graphql api in one",
  Elysia: "bun first server, typed end to end", h3: "the http layer under nitro",
  Nitro: "nuxt's server, deployable anywhere", Capacitor: "web app in a native shell",
  Quasar: "vue framework with its own components", Vike: "vite's own framework layer",
  "TanStack Start": "full stack react on tanstack router", Feathers: "realtime api framework",
  restify: "http api server", polka: "express api, much smaller",
  Immer: "write mutations, get an immutable copy", "Redux Saga": "side effects as generators",
  RxJS: "streams and operators", Signals: "fine grained reactivity",
  "Legend State": "signals with persistence", "TanStack Store": "framework agnostic store",
  "React Hook Form": "forms without rerenders", "TanStack Form": "typed forms",
  HeroUI: "component kit, formerly nextui", Ariakit: "unstyled accessible primitives",
  Fluent: "microsoft's design system", Carbon: "ibm's design system",
  Blueprint: "dense desktop style components", "React Aria": "adobe's accessible primitives",
  Lucide: "icon set, feather fork", "React Icons": "many icon sets in one package",
  Tabler: "icon set", Phosphor: "icon set", Motion: "animation, formerly framer motion",
  "React Spring": "spring physics animation", GSAP: "timeline animation",
  cmdk: "command palette", Sonner: "toasts", Vaul: "drawers",
  "dnd kit": "drag and drop", "TanStack Table": "headless tables", "AG Grid": "data grid",
  Embla: "carousel", Kysely: "typed sql builder", TypeORM: "decorator orm",
  Sequelize: "the older node orm", Knex: "query builder and migrations",
  libSQL: "sqlite over the network", Neon: "serverless postgres",
  PlanetScale: "mysql platform", "Vercel Postgres": "postgres from vercel",
  Upstash: "serverless redis", MongoDB: "document database",
  Elasticsearch: "search engine", Meilisearch: "search engine, lighter",
  Algolia: "hosted search", Nodemailer: "smtp from node", Resend: "transactional email api",
  SendGrid: "email api", Twilio: "sms and voice", Slack: "posts into slack",
  Discord: "bot or webhook", "AI SDK": "vercel's model interface",
  LangChain: "chains and agents", LlamaIndex: "retrieval over your data",
  Ollama: "models running locally", Gemini: "google's models", Mistral: "mistral's models",
  Replicate: "hosted model runs", "Hugging Face": "models and inference",
  "Lemon Squeezy": "payments and licences", LaunchDarkly: "feature flags",
  Unleash: "feature flags, self hosted", GrowthBook: "flags and experiments",
  Statsig: "flags and experiments", MSW: "mocks the network in tests",
  nock: "records and replays http", Sinon: "spies, stubs and clocks", Chai: "assertions",
  Puppeteer: "drives chrome", WebdriverIO: "drives every browser", Selenium: "the original driver",
  TestCafe: "browser tests without a driver", Stryker: "mutation testing",
  "fast-check": "property based testing", Faker: "fake data for tests",
  k6: "load testing", Artillery: "load testing", autocannon: "http benchmark",
  c8: "coverage from v8", nyc: "istanbul's runner", unbuild: "library bundler",
  tsdown: "library bundler on rolldown", bunchee: "zero config library bundler",
  microbundle: "tiny library bundler", Rolldown: "rollup rewritten in rust",
  Changesets: "versioning and changelogs for a monorepo", "semantic-release": "releases from commit messages",
  "release-it": "release script", Husky: "git hooks", "lint-staged": "run linters on staged files",
  commitlint: "commit message rules", "simple-git-hooks": "git hooks, smaller than husky",
  TypeDoc: "api docs from types", Knip: "finds unused files, exports and dependencies",
  depcheck: "finds unused dependencies", Madge: "import graph and circular dependencies",
  "dependency-cruiser": "rules about what may import what", "ts-prune": "finds unused exports",
  publint: "checks a package is publishable", "are the types wrong": "checks the types a package ships",
  syncpack: "keeps versions equal across a monorepo", Sherif: "monorepo linter",
  "AWS CDK": "infrastructure as typescript", SST: "aws apps from code",
  Serverless: "the serverless framework", Pulumi: "infrastructure as code",
  Panda: "styles compiled at build time", Stitches: "css in js, compiled",
  Linaria: "zero runtime css in js", "styled-jsx": "scoped css in a component",
  "tailwind-variants": "variants for tailwind classes", Velite: "content as typed data",
  Fumadocs: "docs framework for next", Nextra: "docs from markdown, next based",
  Docusaurus: "docs site, react based", VitePress: "docs site, vite based",
  Keystatic: "content editing in the repo", TinaCMS: "visual editing on git",
  Prismic: "headless cms", "gray-matter": "front matter parser", remark: "markdown pipeline",
  rehype: "html pipeline", Shiki: "syntax highlighting with editor themes",
  Prism: "syntax highlighting", "highlight.js": "syntax highlighting", marked: "markdown parser",
  Bugsnag: "error tracking", Rollbar: "error tracking", LogRocket: "session replay",
  "New Relic": "apm", Prometheus: "metrics", Axiom: "log storage and queries",
  "Grafana Faro": "browser telemetry", consola: "console logger", loglevel: "tiny logger",
  debug: "namespaced debug output", "Better Auth": "auth you host, typescript first",
  WorkOS: "enterprise sso", Kinde: "hosted auth", OpenID: "openid connect client",
  argon2: "password hashing, the current default", "iron session": "signed cookie sessions",
  Stytch: "hosted auth", Keycloak: "auth server you host", PropelAuth: "hosted auth for b2b",
  sockets: "a socket library, by the bare name", pytest: "python's test runner",
}
