// owner: finn
// goal: annotate stack metadata

// prettier-ignore
export const NOTES: Record<string, string> = {
  React: "component library, the default choice", "Next.js": "React with server rendering and routing, by Vercel",
  Nuxt: "Vue with server rendering", Vue: "component framework, template first",
  Svelte: "compiles components away, no runtime", SvelteKit: "Svelte with routing and server rendering",
  Angular: "full framework, opinionated and typed", Solid: "React shaped, fine grained reactivity",
  Astro: "content sites, ships almost no javascript", Remix: "React with web standard data loading",
  Preact: "React api in three kilobytes", "React Native": "React rendering to native mobile",
  Expo: "toolchain around React Native", Electron: "desktop apps in a bundled browser",
  Tauri: "desktop apps in a rust shell", Gatsby: "React static sites, largely superseded",
  Express: "the old default node server", Fastify: "faster node server, schema first",
  NestJS: "Angular shaped backend framework", Koa: "small express successor",
  Hono: "tiny server, runs on edge runtimes", hapi: "configuration first node server",
  Lambda: "functions on aws, no server to run",

  Zustand: "small store, hooks only", Redux: "the classic store, action driven",
  "Redux Toolkit": "redux with the boilerplate removed", MobX: "observable objects, no reducers",
  Jotai: "atomic state, bottom up", Recoil: "atomic state by meta, now quiet",
  Valtio: "proxy state, mutate it directly", XState: "explicit state machines",
  Pinia: "the vue store", "TanStack Query": "server cache, not really client state",
  SWR: "server cache by vercel", Apollo: "graphql client with a cache",
  Effector: "typed reactive store", NgRx: "redux for angular", Vuex: "the old vue store",
  "Nano Stores": "tiny framework agnostic store",

  Tailwind: "utility classes instead of stylesheets", shadcn: "components you copy in and own",
  MUI: "material design components", "Ant Design": "enterprise component set",
  Chakra: "accessible component set", Bootstrap: "the original css framework",
  Radix: "unstyled accessible primitives", "Base UI": "unstyled primitives, radix successor",
  "Headless UI": "unstyled primitives by tailwind", daisyUI: "tailwind component classes",
  Mantine: "components with hooks", "styled-components": "css in js, tagged templates",
  Emotion: "css in js, the other one", Bulma: "css framework, no javascript",
  PrimeReact: "large component suite", DiceUI: "component set", cva: "variant classes for components",
  NextUI: "component set on tailwind", Vuetify: "material components for vue", Ionic: "mobile shaped components",
  Sass: "css with nesting and variables", Less: "older css preprocessor", Stylus: "terse css preprocessor",
  PostCSS: "css transform pipeline", "vanilla-extract": "typed css, compiled away",
  UnoCSS: "on demand atomic css", clsx: "joins class names", classnames: "joins class names, older",

  axios: "http client, the common one", ky: "small fetch wrapper", got: "node http client",
  "node-fetch": "fetch before node had it", ofetch: "fetch wrapper by nuxt",
  Convex: "hosted reactive database and functions", Prisma: "typed orm with migrations",
  Drizzle: "sql first typed orm", Mongoose: "mongodb models", Postgres: "postgres driver",
  MySQL: "mysql driver", SQLite: "file database, in process", Redis: "in memory store and cache",
  Supabase: "hosted postgres with auth and storage", Firebase: "google hosted backend",
  Directus: "headless data platform", tRPC: "typed rpc without a schema language",
  GraphQL: "query language for apis", "Socket.IO": "realtime channels with fallbacks",
  WebSocket: "raw persistent connection", S3: "object storage on aws", Stripe: "payments",
  OpenAI: "model api", Anthropic: "model api",

  NextAuth: "auth for next, session based", "Auth.js": "framework agnostic auth",
  Clerk: "hosted auth with prebuilt ui", Auth0: "hosted identity provider",
  Passport: "auth strategies for node", JWT: "signed tokens, no session store",
  "Supabase Auth": "auth that ships with supabase", Lucia: "auth you host yourself",
  bcrypt: "password hashing",

  i18n: "translated interface strings", MDX: "markdown that can render components",
  Contentlayer: "typed content from files", Sanity: "hosted structured content",
  Contentful: "hosted headless cms", Storyblok: "hosted visual cms",
  Storybook: "components in isolation", Payload: "cms that lives in the repo",

  Sentry: "error tracking", PostHog: "product analytics and flags",
  "Vercel Analytics": "page and speed metrics", Datadog: "infrastructure monitoring",
  OpenTelemetry: "vendor neutral tracing", Mixpanel: "product analytics",
  Amplitude: "product analytics", pino: "fast json logger", winston: "configurable logger",

  Vitest: "test runner built on vite", Jest: "the long standing test runner",
  Mocha: "older test runner", Playwright: "browser tests across engines",
  Cypress: "browser tests, one engine", "Testing Library": "queries the dom as a user would",
  AVA: "concurrent test runner", Jasmine: "older assertion framework",
  Karma: "browser test runner, retired", supertest: "http assertions against a server",

  Vite: "dev server and bundler, fast", webpack: "the old bundler, still everywhere",
  Turbopack: "next's rust bundler", Rollup: "library bundler", esbuild: "very fast bundler in go",
  Parcel: "zero config bundler", Turborepo: "task cache for monorepos", Nx: "monorepo toolkit",
  Lerna: "older monorepo publisher", tsup: "library builds on esbuild", Rspack: "webpack api in rust",
  SWC: "rust compiler for typescript", Babel: "javascript compiler, plugin driven",
  Gulp: "task runner, older", Grunt: "task runner, retired", Make: "the original build tool",
  just: "a command runner, no build graph", Task: "yaml command runner", Rake: "ruby build tool",

  ESLint: "the standard linter, plugin driven", Biome: "linter and formatter in rust",
  oxlint: "very fast linter in rust", "TSLint (dead)": "retired, replaced by eslint",
  standard: "linter with fixed rules", xo: "eslint with opinions", Stylelint: "linter for css",
  Prettier: "formatter, few options on purpose", oxfmt: "formatter in rust", dprint: "pluggable formatter",

  "GitHub Actions": "ci in the repo, yaml workflows", "GitLab CI": "gitlab pipelines",
  Jenkins: "self hosted ci, older", CircleCI: "hosted ci", Travis: "hosted ci, largely retired",
  "Azure Pipelines": "microsoft ci", Drone: "container native ci",
  Vercel: "deploys on push", Netlify: "deploys on push",

  Bruno: "api collections stored as files", Postman: "api collections, hosted",
  Insomnia: "api client", "REST client": "http requests in plain files",
  OpenAPI: "machine readable api description",

  Node: "the server runtime", Bun: "faster runtime and toolkit", Deno: "secure runtime by node's author",
  Workers: "cloudflare edge runtime", pnpm: "package manager, hard linked store",
  npm: "the default package manager", yarn: "package manager, workspaces first",
  esm: "modern module syntax", cjs: "the older require syntax",
}
